### ISSUE TITLE
snakemake lock directory

### ISSUE THREAD

**Issue by VilenneFrederique** [MUMC-MEDMIC/MACOVID#13]
Hoi Brian,

als ncov_scripts/nextstrain.sh gekilled wordt, dan blijft de working directory gelocked.
dit kan niet verholpen worden met:
```
snakemake --unlock
```
vanuit de ncov folder.
zou je hier een fix voor kunnen maken.

de workaround dat we nu hebben toegpepast is door de --unlock flag toe te voegen in het script, deze dan te runnen en dan dit weer te verwijderen.

mvg,
Casper & Frederique

**Comment by BVeer** [comment]
This is not a MACOVID issue. Also, this is standard behaviour of snakemake
